LABELS = [
    "ADMIN_TRAP",
    "IGNORE",
    "OPTIONAL_BONUS",
    "PRE_REQUISITE",
    "TECHNICAL_TASK",
    "WEIGHTED_PRIORITY",
]


RAW_ID2LABEL = {
    "LABEL_0": "ADMIN_TRAP",
    "LABEL_1": "IGNORE",
    "LABEL_2": "OPTIONAL_BONUS",
    "LABEL_3": "PRE_REQUISITE",
    "LABEL_4": "TECHNICAL_TASK",
    "LABEL_5": "WEIGHTED_PRIORITY",
}
